[tool.black]
target_version = ['py36', 'py37', 'py38', 'py39']
include = '\.pyi?$'
skip-magic-trailing-comma = true
preview = true

exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.eggs
)/
'''
