[tool.black]
target_version = ['py39', 'py310', 'py311', 'py312', 'py313']
include = '\.pyi?$'
skip-magic-trailing-comma = true
preview = true

exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.eggs
)/
'''

[tool.mypy]
warn_unused_ignores = true
exclude = [
  "asynq/tests/typing_example"
]
