[tool.black]
target_version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
skip-magic-trailing-comma = true
preview = true

exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.eggs
)/
'''
